Operation on cuda
Using midjourney DATASET, Classes in dataset: ['ai', 'nature']
Additional tokens : 2
Training...
Loss epoch 0 -> 1.66
/home/users/r/rasolof2/miniconda3/envs/project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/users/r/rasolof2/miniconda3/envs/project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/users/r/rasolof2/miniconda3/envs/project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
Loss epoch 1 -> 0.73
end...
Accuracy : 0.5
Classification report:
              precision    recall  f1-score   support

          ia       0.00      0.00      0.00       500
      nature       0.50      1.00      0.67       500

    accuracy                           0.50      1000
   macro avg       0.25      0.50      0.33      1000
weighted avg       0.25      0.50      0.33      1000

-----------------------------------------------------------------------------------------------------------
Additional tokens : 3
Training...
Loss epoch 0 -> 1.21
/home/users/r/rasolof2/miniconda3/envs/project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/users/r/rasolof2/miniconda3/envs/project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/users/r/rasolof2/miniconda3/envs/project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
Loss epoch 1 -> 0.79
end...
Accuracy : 0.5
Classification report:
              precision    recall  f1-score   support

          ia       0.50      1.00      0.67       500
      nature       0.00      0.00      0.00       500

    accuracy                           0.50      1000
   macro avg       0.25      0.50      0.33      1000
weighted avg       0.25      0.50      0.33      1000

-----------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/users/r/rasolof2/BCs_emmanuelrasolofo/BCs_EmmanuelRasolofo/lab.py", line 131, in <module>
    plot_accuracy()
  File "/home/users/r/rasolof2/BCs_emmanuelrasolofo/BCs_EmmanuelRasolofo/lab.py", line 125, in plot_accuracy
    plt.plot(configurations.ADD_TOKENS_lab, ACC, label='Accuracy_token')
  File "/home/users/r/rasolof2/miniconda3/envs/project/lib/python3.12/site-packages/matplotlib/pyplot.py", line 3827, in plot
    return gca().plot(
           ^^^^^^^^^^^
  File "/home/users/r/rasolof2/miniconda3/envs/project/lib/python3.12/site-packages/matplotlib/axes/_axes.py", line 1777, in plot
    lines = [*self._get_lines(self, *args, data=data, **kwargs)]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/r/rasolof2/miniconda3/envs/project/lib/python3.12/site-packages/matplotlib/axes/_base.py", line 297, in __call__
    yield from self._plot_args(
               ^^^^^^^^^^^^^^^^
  File "/home/users/r/rasolof2/miniconda3/envs/project/lib/python3.12/site-packages/matplotlib/axes/_base.py", line 494, in _plot_args
    raise ValueError(f"x and y must have same first dimension, but "
ValueError: x and y must have same first dimension, but have shapes (2,) and (1,)
srun: error: gpu002: task 0: Exited with exit code 1
